export const FALLBACK_PROMPTS: string[] = [
  'Se você pudesse criar uma matéria nova na escola, qual seria e como ela funcionaria?',
  'E se um dia todos os seus pensamentos aparecessem escritos em um caderno mágico?',
  'Imagine que você acordou com a habilidade de entender os sentimentos das pessoas, o que mudaria no seu dia?',
  'Já pensou se os objetos do seu quarto pudessem contar histórias sobre você?',
  'O que aconteceria se o recreio durasse o dia inteiro por uma semana?',
  'Como você se sentiria se pudesse viajar para qualquer lugar apenas fechando os olhos?',
  'Conte uma história em que um dia comum se transforma em algo inesperado.',
  'Se você pudesse mudar uma pequena coisa no mundo, qual seria e por quê?',
  'E se você encontrasse uma mensagem misteriosa dentro do seu material escolar?',
  'Imagine que hoje você pode viver dentro do seu jogo ou filme favorito por um dia.',
  'Já pensou se cada escolha sua deixasse uma trilha visível pelo caminho?',
  'O que aconteceria se todos tivessem um botão para pausar o tempo por alguns minutos?',
  'Como você se sentiria se descobrisse que é muito bom em algo que nunca tentou antes?',
  'Conte uma história em que um simples passeio se torna uma grande aventura.',
  'Se você pudesse conversar com seu eu do futuro, o que perguntaria?',
  'E se um animal pudesse virar seu melhor amigo e conversar com você?',
  'Imagine que hoje tudo deu certo do jeito que você planejou. Como foi seu dia?',
  'Já pensou se os sonhos pudessem continuar depois que você acorda?',
  'O que aconteceria se você tivesse que explicar seu dia para alguém de outro planeta?',
  'Como você se sentiria se descobrisse um talento escondido em você?',
];
