package com.example.rabisco.ui.theme

import androidx.compose.ui.graphics.Color
// Custom Colors
val DarkPrimary = Color(0xFFb8c4ff)
val DarkSecondary = Color(0xFFc2c5dd)
val DarkTertiary = Color(0xFF95cdf8)

val LightPrimary = Color(0xFF4f5b92)
val LightSecondary = Color(0xFF5a5d72)
val LightTertiary = Color(0xFF276389)


// CORES DE SEGURANÇA (Adicionadas para evitar tela preta)


val primaryLight = Color(0xFF7C93F5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDE1FF)
val onPrimaryContainerLight = Color(0xFF374379)
val secondaryLight = Color(0xFF33618D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E4FF)
val onSecondaryContainerLight = Color(0xFF144974)
val tertiaryLight = Color(0xFF555992)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E0FF)
val onTertiaryContainerLight = Color(0xFF3E4278)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FA)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFF8F9FA)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE2E1EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC6C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF2F0F7)
val inversePrimaryLight = Color(0xFFB8C4FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceBrightLight = Color(0xFFF8F9FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

val primaryDark = Color(0xFFB8C4FF)
val onPrimaryDark = Color(0xFF1F2C61)
val primaryContainerDark = Color(0xFF374379)
val onPrimaryContainerDark = Color(0xFFDDE1FF)
val secondaryDark = Color(0xFF9ECAFC)
val onSecondaryDark = Color(0xFF003256)
val secondaryContainerDark = Color(0xFF144974)
val onSecondaryContainerDark = Color(0xFFD0E4FF)
val tertiaryDark = Color(0xFFBEC2FF)
val onTertiaryDark = Color(0xFF272B60)
val tertiaryContainerDark = Color(0xFF3E4278)
val onTertiaryContainerDark = Color(0xFFE0E0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E1E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E1E9)
val surfaceVariantDark = Color(0xFF45464F)
val onSurfaceVariantDark = Color(0xFFC6C5D0)
val outlineDark = Color(0xFF90909A)
val outlineVariantDark = Color(0xFF45464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF4F5B92)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)